routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
	return view('presentation.index');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => 'auth'], function () {
	Route::resource('user', 'UserController', ['except' => ['show']]);
	Route::get('profile', ['as' => 'profile.edit', 'uses' => 'ProfileController@edit']);
	Route::put('profile', ['as' => 'profile.update', 'uses' => 'ProfileController@update']);
	Route::put('profile/password', ['as' => 'profile.password', 'uses' => 'ProfileController@password']);
});

// Nuetras rutas personalizadas.abnf

Route::resource('good', 'GoodController', ['except' => ['show']]);

// Rutas Innoaire
//Route::resource('presentation', 'InnoairePresentationController', ['except' => ['show']]);

Route::get('/about-us', 'InnoairePresentationController@aboutUs');
Route::get('/presentation', 'InnoairePresentationController@index');
Route::get('/basicActivities', 'InnoairePresentationController@basicActivities');
Route::get('/ourLines', 'InnoairePresentationController@ourLines');
Route::get('/supplies', 'InnoairePresentationController@supplies');
Route::get('/contactUs', 'InnoairePresentationController@contactUs');

/**
 * Rutas para el registro de los datos de quienes somos
 */
Route::resource('whoweares', 'whoWeAreController', ['except' => ['show']]);

app/models/whoWeAre.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class whoWeAre extends Model
{
    protected $fillable = [
        'image',
        'text',
        'mission',
        'vision',
        'social_objective',
        'created_at',
        'updated_at'
        ];
}

app/Http/Controllers/whoWeAreController.php
<?php

namespace App\Http\Controllers;

use App\models\whoWeAre;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\DB;
use Exception;

class whoWeAreController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $whoWeAre = whoWeAre::paginate(5);
        return view('whoweares.index', ['whoweares' => $whoWeAre]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('whoweares.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\models\whoWeAre  $whoWeAre
     * @return \Illuminate\Http\Response
     */
    public function show(whoWeAre $whoWeAre)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\models\whoWeAre  $whoWeAre
     * @return \Illuminate\Http\Response
     */
    public function edit(whoWeAre $whoWeAre)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\models\whoWeAre  $whoWeAre
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, whoWeAre $whoWeAre)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\models\whoWeAre  $whoWeAre
     * @return \Illuminate\Http\Response
     */
    public function destroy(whoWeAre $whoWeAre)
    {
        //
    }
}

resources/views/whoweares/create.blade.php
@extends('layouts.app', ['title' => __('Crean de presentación')])
@section('css')
<link type="text/css" href="{{asset('dropzone/dropzone.min.css')}}" rel="stylesheet">
@stop
@section('content')
    @include('users.partials.header', ['title' => __('Creación de presentación')])   
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Lista de presentación') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('whoweares.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a la lista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('whoweares.store') }}" autocomplete="off">
                            @csrf
                            
                            <h6 class="heading-small text-muted mb-4">{{ __('Informacion del bien') }}</h6>
                            <div class="pl-lg-4">

                            <div class="form-group{{ $errors->has('image') ? ' has-danger' : '' }}">
                                    <form action="{{ route('whoweares.store') }}"
    class="dropzone" id="my-awesome-dropzone">
      {{ csrf_field() }}
</form> 
                                </div>

                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Nombre') }}" value="{{ old('name') }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-description">{{ __('Descripción') }}</label>
                                    <textarea rows="4" cols="50" type="text" name="description" id="input-description" class="form-control form-control-alternative{{ $errors->has('description') ? ' is-invalid' : '' }}" placeholder="{{ __('Descripción') }}" value="{{ old('description') }}" required autofocus>
                                        </textarea>
                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="form-group{{ $errors->has('value') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-value">{{ __('Valor') }}</label>
                                    <input type="number" name="value" id="input-value" class="form-control form-control-alternative{{ $errors->has('value') ? ' is-invalid' : '' }}" placeholder="{{ __('Valor') }}" value="{{ old('value') }}" required>

                                    @if ($errors->has('value'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('value') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div> 
        <!-- <form action="{{ route('whoweares.store') }}"
    class="dropzone" id="my-awesome-dropzone">
      {{ csrf_field() }}
</form> -->
        
        
        @include('layouts.footers.auth')
    </div>
@endsection

@section('script')
<script src="{{asset('dropzone/dropzone.js')}}">

Dropzone.options.myAwesomeDropzone = {
    paramName: "file", // Las imágenes se van a usar bajo este nombre de parámetro
    maxFilesize: 2, // Tamaño máximo en MB
    success: function (file, response) {
        console.log(response);
    }
};
</script>


@endsection

resources/views/whoweares/edit.blade.php
@extends('layouts.app', ['title' => __('Actualizacion de bien')])

@section('content')
    @include('users.partials.header', ['title' => __('Actualizar bien')])   

    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col-xl-12 order-xl-1">
                <div class="card bg-secondary shadow">
                    <div class="card-header bg-white border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Lista de bienes') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('good.index') }}" class="btn btn-sm btn-primary">{{ __('Volver a lalista') }}</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post" action="{{ route('good.update', $good) }}" autocomplete="off">
                            @csrf
                            @method('put')
                            <h6 class="heading-small text-muted mb-4">{{ __('Informacion del bien') }}</h6>
                            <div class="pl-lg-4">
                                <div class="form-group{{ $errors->has('name') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-name">{{ __('Nombre') }}</label>
                                    <input type="text" name="name" id="input-name" class="form-control form-control-alternative{{ $errors->has('name') ? ' is-invalid' : '' }}" placeholder="{{ __('Name') }}" value="{{ old('name', $good->name) }}" required autofocus>

                                    @if ($errors->has('name'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('name') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                <div class="form-group{{ $errors->has('description') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-description">{{ __('Descripción') }}</label>
                                    <textarea rows="4" cols="50" type="text" name="description" id="input-description" class="form-control form-control-alternative{{ $errors->has('description') ? ' is-invalid' : '' }}" placeholder="{{ __('Descripción') }}" value="{{ old('description', $good->description) }}" required autofocus>{{$good->description}}
                                        </textarea>
                                    @if ($errors->has('description'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('description') }}</strong>
                                        </span>
                                    @endif
                                </div>
                                
                                <div class="form-group{{ $errors->has('value') ? ' has-danger' : '' }}">
                                    <label class="form-control-label" for="input-value">{{ __('Valor') }}</label>
                                    <input type="number" name="value" id="input-value" class="form-control form-control-alternative{{ $errors->has('value') ? ' is-invalid' : '' }}" placeholder="{{ __('Valor') }}" value="{{ old('value',$good->value) }}" required>

                                    @if ($errors->has('value'))
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $errors->first('value') }}</strong>
                                        </span>
                                    @endif
                                </div>

                                <div class="text-center">
                                    <button type="submit" class="btn btn-success mt-4">{{ __('Guardar') }}</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
        
        @include('layouts.footers.auth')
    </div>
@endsection

resources/views/whoweares/index.blade.php
@extends('layouts.app', ['title' => __('Quienes somos')])
@section('css')
<link type="text/css" href="{{asset('css/mycss.css')}}" rel="stylesheet">
@stop
@section('content')
    <div class="header bg-gradient-primary pb-8 pt-5 pt-md-8">
        <div class="container-fluid">
            <div class="header-body">
                <div class="row">

                </div>
            </div>
        </div>
    </div>
    <div class="container-fluid mt--7">
        <div class="row">
            <div class="col">
                <div class="card shadow">
                    <div class="card-header border-0">
                        <div class="row align-items-center">
                            <div class="col-8">
                                <h3 class="mb-0">{{ __('Quienes somos') }}</h3>
                            </div>
                            <div class="col-4 text-right">
                                <a href="{{ route('whoweares.create') }}" class="btn btn-sm btn-primary">{{ __('Crear Presentación') }}</a>
                            </div> 
                        </div>
                    </div>
                    
                    <div class="col-12">
                        @if (session('status'))
                            <div class="alert alert-success alert-dismissible fade show" role="alert">
                                {{ session('status') }}
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        @endif
                    </div>

                    <div class="table-responsive">
                        <table class="table align-items-center table-flush">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">{{ __('Imagen') }}</th>
                                    <th class="col-sm-2">{{ __('Descripción') }}</th>
                                    <th scope="col">{{ __('Misión') }}</th>
                                    <th scope="col">{{ __('Visión') }}</th>
                                    <th scope="col">{{ __('Objetivo Social') }}</th>
                                    <th scope="col"></th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach ($whoweares as $whoweare)
                                    <tr>
                                        <td  width="5" height="5">{{ $whoweare->image }}</td>
                                        <td class="mycssTDs">
                                         {{ $whoweare->text }}
                                        </td>
                                        <td class="mycssTDs">{{ $whoweare->mission }}</td>
                                        <td class="mycssTDs">{{ $whoweare->vision}}</td>
                                        <td class="mycssTDs">{{ $whoweare->social_objective}}</td>
                                        <td class="text-right">
                                            <div class="dropdown">
                                                <a class="btn btn-sm btn-icon-only text-light" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                    <i class="fas fa-ellipsis-v"></i>
                                                </a>
                                                <div class="dropdown-menu dropdown-menu-right dropdown-menu-arrow">
                                                      
                                                            <a class="dropdown-item" href="{{ route('whoweares.edit', $whoweare) }}">{{ __('Actualizar') }}</a>
                                                            <!-- <button type="button" class="dropdown-item" onclick="confirm('{{ __(" Estás seguro de que deseas eliminar a este BIEN?") }}') ? this.parentElement.submit() : ''">
                                                                {{ __('Eliminar') }}
                                                            </button> -->
                                                    
                                                </div>
                                            </div>
                                        </td>
                                    </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="card-footer py-4">
                        <nav class="d-flex justify-content-end" aria-label="...">
                            {{ $whoweares->links() }}
                        </nav>
                    </div>
                </div>
            </div>
        </div>
            
        @include('layouts.footers.auth')
    </div>
@endsection